version: "3.9"
services:
  useritem-api-service-test:
    image: brentpulmansTM/python-db-test-BP
    ports:
      - "8000:8000"
    volumes:
      - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume:
